hangman game code
grantjenks/free-python-games pull request #91
Opened 2022-11-11 11:46 UTC by BaekMinHyeon

I made a hangman in the issue.
I'd appreciate it if you could give me a feed. thanks

If the code is satisfactory to you, I will also create test code and documentation 

ps. If you want an answer to Exercise 4, I'll post an example answer in the comments as well.

2022-11-30 07:05 UTC, grantjenks requested changes
This game is pretty fun. I played a copy of it and enjoyed myself. I left a number of comments. Overall, try to simplify the game further. Remove features if you have to. But keep it fun.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +    if straight == True:
```suggestion
    if straight:
```

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +    elif straight == False:
```suggestion
    else:
```

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +def drawHangman(num):
Use snake_case like `draw_hangman`

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +        """draw head"""
Use comments, not strings like `# Draw head`. Same for other strings in this function.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +def drawHangman(num):
Change `num` to `step` to reflect that each of these is the next step in drawing the overall picture.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +        'tomato', 'watermelon']
Start with just 5 or 10 words. Keep it to 1-2 lines.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +        letter = textinput("Hangman","Guess a letter:")
Rather than using `textinput`, simply respond to key press instead.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +    if letter not in use:
Remove this check. Allow someone to guess the same letter twice. It's dumb but it'll just lose a turn.

2022-11-30 07:05 UTC, grantjenks commented on freegames/hangman.py
> +        move_write(-200, -100, "You use alphbet: ")
```suggestion
        move_write(-200, -100, "Guesses: ")
```

2022-11-30 07:17 UTC, BaekMinHyeon commented
Thanks for your feedback, I will reflect your feedback and post it as soon as possible.

2022-11-30 07:25 UTC, BaekMinHyeon commented on freegames/hangman.py
> +3. Convert lowercase letters to uppercase letters
This means that the words on the screen are lowercase, but students can try to change uppercase

2022-12-02 11:46 UTC, BaekMinHyeon commented
I have corrected all the feedback you gave me
And modified to receive input with key press without using testinput

2022-12-04 01:48 UTC, BaekMinHyeon commented
I created a docs about hangman

2022-12-27 03:53 UTC, merged