typing game code
grantjenks/free-python-games pull request #92
Opened 2022-11-24 12:35 UTC by hanwooseok1

Typing game is a game that removes falling letters from the screen by typing the same letters.
Entering the same letter increases your score, and entering different letters decreases your score.
The game is over when the letters fall on the bottom of the screen.

I would appreciate it if you could give me feedback. Thank you.

2022-11-30 07:13 UTC, grantjenks requested changes
Fun game! I like how simple it is. Left a few comments.

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +                break
Why not simply do `letter = random.choice(string.ascii_lowercase)` ?

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +    ontimer(move, 50)
Default should move a little more slowly. Like `ontimer(move, 100)`

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +        letters.pop(k)
Prefer `del` instead since the return value of `pop` doesn't matter here.

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +        print('\rscore:', score, end = '\t')
Don't use `\r`, it's just more to explain to students. Just print the score with a regular newline.

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +onkey(lambda: press('z'), 'z')
```suggestion
for letter in string.ascii_lowercase:
    onkey(lambda: press(letter), letter)
```

2022-11-30 07:13 UTC, grantjenks commented on freegames/typing.py
> +from freegames import vector
Add `from string import ascii_lowercase as letters` and then use `letters` throughout the program instead of `string.ascii_lowercase` as I've done.

2022-12-02 15:13 UTC, hanwooseok1 commented
https://github.com/grantjenks/free-python-games/blob/8d9e4a8043647117f1388115641adf4d2c620919/freegames/typing.py#L70-L95
I would be very grateful if you could check this out.

2022-12-05 01:55 UTC, hanwooseok1 commented
I added typing.rst about typing.py.

2022-12-27 03:54 UTC, merged