Add Avoid game
grantjenks/free-python-games pull request #93
Opened 2022-11-25 11:03 UTC by SongJungHyun1004

Avoid is a simple game that a person avoid things from four directions.

It would be appreciated if you could give me some feedback.

2022-11-30 07:17 UTC, grantjenks requested changes
It's an interesting game. But it's too hard currently. Also code is too redundant with `bombs[1-4]`. Simply to one `bombs` list instead.

2022-11-30 07:17 UTC, grantjenks commented on freegames/avoid.py
> +bombs4 = []
Why track all four? Better to condense to a single list.

2022-11-30 07:17 UTC, grantjenks commented on freegames/avoid.py
> +    if randrange(5) == 0:
Too many bombs by default!

2022-11-30 07:17 UTC, grantjenks commented on freegames/avoid.py
> +        if abs(bomb1 - person) < 15 or abs(bomb2 - person) < 15 or abs(bomb3 - person) < 15 or abs(bomb4 - person) < 15 :
I think the `freegames.vector` data type has an `overlap` method that you can use instead.

2022-12-02 11:31 UTC, SongJungHyun1004 commented
First of all, I really appreciate for your feedback.

I corrected the redundant four list code.
But I don't know what to do about  freegames.vector  **overlap** method you said.
I couldn't find that method in https://grantjenks.com/docs/freegames/api.html#vectors

2022-12-04 23:12 UTC, SongJungHyun1004 commented
And I added **avoid.rst** file to docs.

2022-12-27 03:56 UTC, merged